name: Sitemap and IndexNow
on:
  push:
    branches: [ main ] # Change to master if that is your default branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://believersunite.com/ # REPLACE THIS
          include-html: true
          storage-location: .

      - name: Commit and Push Sitemap
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add sitemap.xml
          git commit -m "Update sitemap" || echo "No changes"
          git push

      - name: Ping IndexNow
        run: |
          # This pings Bing and tells them to check your sitemap
          curl "https://www.bing.com/indexnow?url=https://believersunite.com/sitemap.xml&key=${{ secrets.INDEXNOW_KEY }}"
          # This also pings Yandex (another IndexNow partner)
          curl "https://yandex.com/indexnow?url=https://believersunite.com/sitemap.xml&key=${{ secrets.INDEXNOW_KEY }}"
